name: build

on:
  pull_request:
  push:

env:
  DOTNET_VERSION: 7.0.304

jobs:
  build-nix:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build
      run: ./build.sh --target Build
    - name: Test
      run: ./build.sh --target Tests
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build
      run: .\build.ps1 --target Build
    - name: Test
      run: .\build.ps1 --target Tests
