name: publish-nightly

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.202
    - name: Pack Perfolizer
      run: dotnet pack --configuration Release /p:PrereleaseLabel=-nightly.$GITHUB_RUN_NUMBER src/Perfolizer/Perfolizer/Perfolizer.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:ContinuousIntegrationBuild=true
    - name: Publish nupkg
      env:
        MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
      run: dotnet nuget push **/*.nupkg --source https://www.myget.org/F/perfolizer/api/v3/index.json --api-key $MYGET_API_KEY --timeout 600
    - name: Publish snupkg
      env:
        MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
      run: dotnet nuget push **/*.snupkg --source https://www.myget.org/F/perfolizer/api/v3/index.json --api-key $MYGET_API_KEY --timeout 600